const DETAILED_POSITIONS = {
  //Arsenal
  "David Raya": "GK",
  "Neto": "GK",
  "Kai Havertz": "ST",
  "Bukayo Saka": "RW",
  "Gabriel Jesus": "ST",
  "Jorginho": "CM",
  "Martin Odegaard": "CAM",
  "Gabriel Magalhaes": "LCB",
  "Jurrien Timber": "RB",
  "William Saliba": "RCB",
  "Gabriel Martinelli": "LW",
  "Leandro Trossard": "LW",
  "Thomas Partey": "CDM",
  "Declan Rice": "CDM",
  "Jakub Kiwior": "CB",
  "Takehiro Tomiyasu": "RB",
  "Oleksandr Zinchenko": "LB",
  "Raheem Sterling": "LW",
  "Myles Lewis-Skelly": "LB",
  "Ethan Nwaneri": "RW",
  "Maldini Kacurri": "CB",

  //Aston Villa
  "Emiliano Martinez": "GK",
  "Robin Olsen": "GK",
  "Matty Cash": "RB",
  "Pau Torres": "LCB",
  "Ezri Konsa": "RCB",
  "Lucas Digne": "LB",
  "Alex Moreno": "LB",
  "Boubacar Kamara": "CDM",
  "John McGinn": "CM",
  "Youri Tielemans": "CM",
  "Amadou Onana": "CM",
  "Morgan Rogers": "CAM",
  "Ollie Watkins": "ST",
  "Jhon Duran": "ST",
  "Leon Bailey": "RW",
  " Emiliano Buendia": "CAM",
  "Diego Carlos": "CB",
  "Ian Maatsen": "LB",
  "Ross Barkley": "CM",
  "Lamar Bogarde": "CB",

  //Bournemouth
  "Neto": "GK",
  "Mark Travers": "GK",
  "Adam Smith": "RB",
  "Dean Huijsen": "RCB",
  "Marcos Senesi": "LCB",
  "Illia Zabarnyi": "RCB",
  "Milos Kerkez": "LB",
  "Lewis Cook": "CM",
  "Ryan Christie": "CM",
  "Marcus Tavernier": "LW",
  "Justin Kluivert": "RW",
  "Dango Ouattara": "RW",
  "Evanilson": "ST",
  "Dominic Solanke": "ST",
  "Antoine Semenyo": "ST",
  "David Brooks": "RW",
  "Luis Sinisterra": "LW",
  "Philip Billing": "CM",
  "Julian Araujo": "RB",
  "Max Aarons": "RB",
  "James Hill": "CB",
  "Alex Scott": "CM",

  //Brentford
  "Mark Flekken": "GK",
  "Hector": "GK",
  "Kristoffer Ajer": "CB",
  "Ethan Pinnock": "LCB",
  "Ben Mee": "CB",
  "Mads Roerslev": "RB",
  "Rico Henry": "LB",
  "Sergi Canos": "RW",
  "Vitaly Janelt": "CM",
  "Christian Norgaard": "CDM",
  "Mathias Jensen": "CM",
  "Bryan Mbeumo": "RW",
  "Yoane Wissa": "ST",
  "Ivan Toney": "ST",
  "Neal Maupay": "ST",
  "Kevin Schade": "LW",
  "Mikkel Damsgaard": "CAM",
  "Frank Onyeka": "CM",
  "Ben Godfrey": "CB",
  "Gustavo Nunes": "LW",
  "Keane Lewis-Potter": "LW",
  "Josh Dasilva": "CM",

  //Brighton
  "Jason Steele": "GK",
  "Verbruggen": "GK",
  "Tariq Lamptey": "RB",
  "Joel Veltman": "CB",
  "Lewis Dunk": "RCB",
  "Jan Paul van Hecke": "LCB",
  "Pervis Estupinan": "LB",
  "Valentin Barco": "LB",
  "Billy Gilmour": "CDM",
  "Carlos Baleba": "CDM",
  "Moises Caicedo": "CDM",
  "James Milner": "CM",
  "Kaoru Mitoma": "LW",
  "Simon Adingra": "RW",
  "Danny Welbeck": "ST",
  "Evan Ferguson": "ST",
  "Joao Pedro": "ST",
  "Ansu Fati": "LW",
  "Facundo Buonanotte": "CAM",
  "Adam Lallana": "CM",
  "Jack Hinshelwood": "RB",
  "Jakub Moder": "CM",
  "Yankuba Minteh": "RW",
  "Messrs": "CM",
  "Amario Cozier-Duberry": "RW",

  //Chelsea
  "Robert Sanchez": "GK",
  "Filip Jorgensen": "GK",
  "Reece James": "RB",
  "Wesley Fofana": "RCB",
  "Levi Colwill": "LCB",
  "Benoit Badiashile": "CB",
  "Marc Cucurella": "LB",
  "Malcol Ealo": "LB",
  "Moises Caicedo": "CDM",
  "Romeo Lavia": "CDM",
  "Enzo Fernandez": "CM",
  "Cole Palmer": "CAM",
  "Noni Madueke": "RW",
  "Pedro Neto": "LW",
  "Mykhailo Mudryk": "LW",
  "Nicolas Jackson": "ST",
  "Christopher Nkunku": "ST",
  "Joao Felix": "ST",
  "Kiernan Dewsbury-Hall": "CM",
  "Carney Chukwuemeka": "CM",
  "Renato Veiga": "LB",
  "Axel Disasi": "CB",
  "Tosin Adarabioyo": "CB",

  //Crystal Palace
  "Dean Henderson": "GK",
  "Remi Matthews": "GK",
  "Joel Ward": "RB",
  "Marc Guehi": "RCB",
  "Joachim Andersen": "LCB",
  "Chris Richards": "CB",
  "Tyrick Mitchell": "LB",
  "Daniel Munoz": "RB",
  "Cheick Doucoure": "CDM",
  "Will Hughes": "CM",
  "Jeffrey Schlupp": "CM",
  "Adam Wharton": "CM",
  "Eberechi Eze": "CAM",
  "Michael Olise": "RW",
  "Jean-Philippe Mateta": "ST",
  "Odsonne Edouard": "ST",
  "Jordan Ayew": "ST",
  "Ismaila Sarr": "RW",
  "Jeffrey Schlupp": "LW",
  "Nathaniel Clyne": "RB",
  "Joel Ward": "RB",
  "Kaden Rodney": "CM",

  //Everton
  "Jordan Pickford": "GK",
  "Asmir Begovic": "GK",
  "James Tarkowski": "RCB",
  "Ben Godfrey": "CB",
  "Jarrad Branthwaite": "LCB",
  "Michael Keane": "CB",
  "Vitaliy Mykolenko": "LB",
  "Ashley Young": "RB",
  "Seamus Coleman": "RB",
  "Amadou Onana": "CM",
  "Idrissa Gueye": "CDM",
  "James Garner": "CM",
  "Abdoulaye Doucoure": "CM",
  "Jack Harrison": "RW",
  "Demarai Gray": "LW",
  "Dominic Calvert-Lewin": "ST",
  "Beto": "ST",
  "Armando Broja": "ST",
  "André Gomes": "CM",
  "Nathan Patterson": "RB",
  "Youssef Chermiti": "ST",
  "Harrison Armstrong": "CM",

  //Fulham
  "Bernd Leno": "GK",
  "Marek Rodak": "GK",
  "Kenny Tete": "RB",
  "Tosin Adarabioyo": "RCB",
  "Calvin Bassey": "LCB",
  "Tim Ream": "CB",
  "Antonee Robinson": "LB",
  "Harrison Reed": "CM",
  "Joao Palhinha": "CDM",
  "Sasa Lukic": "CM",
  "Andreas Pereira": "CAM",
  "Harry Wilson": "RW",
  "Adama Traore": "RW",
  "Willian": "LW",
  "Alex Iwobi": "LW",
  "Raul Jimenez": "ST",
  "Carlos Vinicius": "ST",
  "Raheem Sterling": "LW",
  "Emile Smith Rowe": "CAM",
  "Sander Berge": "CM",
  "Ryan Sessegnon": "LB",
  "Issa Diop": "CB",

  //Ipswich Town
  "Arijanet Muric": "GK",
  "Christian Walton": "GK",
  "Ben Johnson": "RB",
  "Luke Woolfenden": "RCB",
  "Jacob Greaves": "LCB",
  "Dara O'Shea": "CB",
  "Leif Davis": "LB",
  "Wes Burns": "RW",
  "Sam Morsy": "CDM",
  "Massimo Luongo": "CM",
  "Sam Szmodics": "CAM",
  "Omari Hutchinson": "RW",
  "Jack Clarke": "LW",
  "Liam Delap": "ST",
  "George Hirst": "ST",
  "Nathan Broadhead": "ST",
  "Chiedozie Ogbene": "RW",
  "Kalvin Phillips": "CDM",
  "Conor Townsend": "LB",
  "Axel Tuanzebe": "CB",
  "Jens Cajuste": "CM",
  "Cameron Humphreys": "CM",

  //Leicester City
  "Jakub Stolarczyk": "GK",
  "Danny Ward": "GK",
  "Conor Coady": "RCB",
  "Wout Faes": "LCB",
  "Jannik Vestergaard": "CB",
  "Luke Thomas": "LB",
  "Ricardo Pereira": "RB",
  "James Justin": "RB",
  "Wilfred Ndidi": "CDM",
  "Harry Winks": "CM",
  "Kiernan Dewsbury-Hall": "CM",
  "Boubakary Soumare": "CM",
  "Abdul Fatawu Issahaku": "RW",
  "Stephy Mavididi": "LW",
  "Jamie Vardy": "ST",
  "Patson Daka": "ST",
  "Kelechi Iheanacho": "ST",
  "Facundo Buonanotte": "CAM",
  "Jordan Ayew": "ST",
  "Hamza Choudhury": "CM",
  "Ben Nelson": "CB",
  "Kasey McAteer": "RW",

  //Liverpool
  "Alisson Becker": "GK",
  "Caoimhin Kelleher": "GK",
  "Trent Alexander-Arnold": "RB",
  "Virgil van Dijk": "LCB",
  "Ibrahima Konate": "RCB",
  "Jarell Quansah": "CB",
  "Andrew Robertson": "LB",
  "Kostas Tsimikas": "LB",
  "Alexis Mac Allister": "CM",
  "Dominik Szoboszlai": "CM",
  "Ryan Gravenberch": "CDM",
  "Wataru Endo": "CDM",
  "Curtis Jones": "CM",
  "Mohamed Salah": "RW",
  "Luis Diaz": "LW",
  "Diogo Jota": "ST",
  "Darwin Nunez": "ST",
  "Cody Gakpo": "LW",
  "Harvey Elliott": "CAM",
  "Andy Robertson": "LB",
  "Conor Bradley": "RB",
  "Tyler Morton": "CM",

  //Manchester City
  "Ederson": "GK",
  "Stefan Ortega": "GK",
  "Kyle Walker": "RB",
  "Ruben Dias": "RCB",
  "John Stones": "CB",
  "Manuel Akanji": "CB",
  "Nathan Ake": "LCB",
  "Josko Gvardiol": "LB",
  "Rico Lewis": "RB",
  "Rodri": "CDM",
  "Kevin De Bruyne": "CAM",
  "Bernardo Silva": "CM",
  "Ilkay Gundogan": "CM",
  "Mateo Kovacic": "CM",
  "Phil Foden": "CAM",
  "Jeremy Doku": "LW",
  "Savinho": "RW",
  "Erling Haaland": "ST",
  "Jack Grealish": "LW",
  "Omar Marmoush": "ST",
  "James McAtee": "CAM",
  "Joshua Wilson-Esbrand": "LB",

  //Manchester United
  "Andre Onana": "GK",
  "Altay Bayindir": "GK",
  "Matthijs de Ligt": "RCB",
  "Lisandro Martinez": "LCB",
  "Jonny Evans": "CB",
  "Harry Maguire": "CB",
  "Noussair Mazraoui": "RB",
  "Diogo Dalot": "RB",
  "Luke Shaw": "LB",
  "Tyrell Malacia": "LB",
  "Manuel Ugarte": "CDM",
  "Kobbie Mainoo": "CM",
  "Bruno Fernandes": "CAM",
  "Christian Eriksen": "CM",
  "Casemiro": "CDM",
  "Amad Diallo": "RW",
  "Alejandro Garnacho": "LW",
  "Marcus Rashford": "LW",
  "Rasmus Hojlund": "ST",
  "Joshua Zirkzee": "ST",
  "Antony": "RW",
  "Leny Yoro": "CB",
  "Ayden Heaven": "CB",

  //Newcastle United
  "Nick Pope": "GK",
  "Martin Dubravka": "GK",
  "Kieran Trippier": "RB",
  "Fabian Schar": "RCB",
  "Sven Botman": "LCB",
  "Dan Burn": "CB",
  "Lewis Hall": "LB",
  "Matt Targett": "LB",
  "Bruno Guimaraes": "CM",
  "Sandro Tonali": "CM",
  "Joelinton": "CM",
  "Sean Longstaff": "CM",
  "Sandro Tonali": "CM",
  "Anthony Gordon": "LW",
  "Jacob Murphy": "RW",
  "Alexander Isak": "ST",
  "Callum Wilson": "ST",
  "Harvey Barnes": "LW",
  "Miguel Almiron": "RW",
  "Joe Willock": "CM",
  "Lewis Miley": "CM",
  "Lloyd Kelly": "CB",
  "Emil Krafth": "RB",

  //Nottingham Forest
  "Matz Sels": "GK",
  "Carlos Miguel": "GK",
  "Ola Aina": "RB",
  "Murillo": "RCB",
  "Neco Williams": "LB",
  "Moussa Niakhate": "LCB",
  "Willy Boly": "CB",
  "Andrew Omobamideley": "CB",
  "Ibrahim Sangare": "CDM",
  "Ryan Yates": "CM",
  "Danilo": "CM",
  "Nicolas Dominguez": "CM",
  "Elliot Anderson": "CM",
  "Morgan Gibbs-White": "CAM",
  "Anthony Elanga": "RW",
  "Callum Hudson-Odoi": "LW",
  "Chris Wood": "ST",
  "Taiwo Awoniyi": "ST",
  "Jota Silva": "LW",
  "James Ward-Prowse": "CM",
  "Alex Moreno": "LB",
  "Eric da Silva Moreira": "RW",

  //Southampton
  "Aaron Ramsdale": "GK",
  "Lumley": "GK",
  "Kyle Walker-Peters": "RB",
  "Jan Bednarek": "RCB",
  "Yan Valery": "CB",
  "Jack Stephens": "LCB",
  "Ryan Manning": "LB",
  "Sugawara": "RB",
  "James Bree": "CB",
  "Carlos Alcaraz": "CM",
  "Adam Armstrong": "ST",
  "Che Adams": "ST",
  "Kamaldeen Sulemana": "LW",
  "Samuel Edozie": "LW",
  "Ross Stewart": "ST",
  "Joe Aribo": "CM",
  "Flynn Downes": "CM",
  "Mateus Fernandes": "CM",
  "Ryan Fraser": "LW",
  "Paul Onuachu": "ST",
  "Cody Draper": "CM",
  "Tyler Dibling": "RW",

  //Tottenham Hotspur
  "Guglielmo Vicario": "GK",
  "Fraser Forster": "GK",
  "Cristian Romero": "RCB",
  "Micky van de Ven": "LCB",
  "Ben Davies": "CB",
  "Radu Dragusin": "CB",
  "Destiny Udogie": "LB",
  "Pedro Porro": "RB",
  "Rodrigo Bentancur": "CDM",
  "Yves Bissouma": "CDM",
  "James Maddison": "CAM",
  "Dejan Kulusevski": "CAM",
  "Pape Matar Sarr": "CM",
  "Brennan Johnson": "RW",
  "Son Heung-min": "LW",
  "Richarlison": "ST",
  "Dominic Solanke": "ST",
  "Tim Werner": "LW",
  "Lucas Bergvall": "CM",
  "Djed Spence": "RB",
  "Archie Gray": "CM",
  "Wilson Odobert": "LW",

  //West Ham United
  "Alphonse Areola": "GK",
  "Lukasz Fabianski": "GK",
  "Aaron Wan-Bissaka": "RB",
  "Jean-Clair Todibo": "RCB",
  "Max Kilman": "LCB",
  "Emerson Palmieri": "LB",
  "Aaron Cresswell": "LB",
  "Edson Alvarez": "CDM",
  "Lucas Paqueta": "CM",
  "Guido Rodriguez": "CDM",
  "Tomáš Souček": "CM",
  "Jarrod Bowen": "RW",
  "Mohammed Kudus": "CAM",
  "Crysencio Summerville": "LW",
  "Niclas Fullkrug": "ST",
  "Michail Antonio": "ST",
  "Danny Ings": "ST",
  "Lucas Paqueta": "CM",
  "Carlos Soler": "CM",
  "Wanderson": "LB",
  "Konstantinos Mavropanos": "CB",
  "Oliver Scarles": "LB",

  //Wolverhampton Wanderers
  "Jose Sa": "GK",
  "Daniel Bentley": "GK",
  "Nelson Semedo": "RB",
  "Max Kilman": "RCB",
  "Craig Dawson": "CB",
  "Toti Gomes": "LB",
  "Rayan Ait-Nouri": "LB",
  "Mario Lemina": "CDM",
  "Joao Gomes": "CM",
  "Boubacar Traore": "CM",
  "Pablo Sarabia": "CAM",
  "Hee-Chan Hwang": "ST",
  "Matheus Cunha": "ST",
  "Jhon Strand Larsen": "ST",
  "Pedro Neto": "RW",
  "Daniel Podence": "LW",
  "Sasa Kalajdzic": "ST",
  "Enso Gonzalez": "LW",
  "Jean-Ricner Bellegarde": "CM",
  "Nathan Fraser": "ST",
  "Matt Doherty": "RB",
  "Yerson Mosquera": "CB",
  "Pedro Lima": "RB"
};

const ZONE_MAP = {
  "GK": "gk",
  "LB": "lb", "RB": "rb",
  "CB": "lcb", "LCB": "lcb", "RCB": "rcb",
  "LWB": "lb", "RWB": "rb",
  "CDM": "ldm", "DM": "ldm",
  "LM": "lw", "CM": "ldm", "RM": "rw",
  "CAM": "cam",
  "LW": "lw", "RW": "rw",
  "LF": "lw", "CF": "st", "RF": "rw",
  "ST": "st", "SS": "st"
};

const ZONE_GROUP = {
  gk: 'gk',
  lb: 'defence', lcb: 'defence', rcb: 'defence', rb: 'defence',
  ldm: 'midfield', rdm: 'midfield',
  lw: 'attack', cam: 'attack', rw: 'attack', st: 'attack'
};

const POSITION_LABELS = {
  "GK": "GK", "CB": "CB", "LCB": "LCB", "RCB": "RCB",
  "LB": "LB", "RB": "RB",
  "CDM": "CDM", "DM": "CDM",
  "CM": "CM",
  "CAM": "CAM",
  "LW": "LW", "RW": "RW",
  "ST": "ST"
};

const ZONE_LABELS = {
  gk: "GK",
  lb: "LB", lcb: "LCB", rcb: "RCB", rb: "RB",
  ldm: "LDM", rdm: "RDM",
  lw: "LW", cam: "CAM", rw: "RW", st: "ST"
};

const ATTACKING_ZONES = ["lw", "cam", "rw", "st"];
const DEFENSIVE_ZONES = ["lb", "lcb", "rcb", "rb"];
const MIDFIELD_ZONES = ["ldm", "rdm"];
const ALL_ZONES = ["gk", "lb", "lcb", "rcb", "rb", "ldm", "rdm", "lw", "cam", "rw", "st"];

module.exports = { DETAILED_POSITIONS, ZONE_MAP, ZONE_LABELS, ZONE_GROUP, POSITION_LABELS, ATTACKING_ZONES, DEFENSIVE_ZONES, MIDFIELD_ZONES, ALL_ZONES };
